import {
  ArrowLeftRight,
  Banknote,
  Bitcoin,
  Briefcase,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  Coins,
  CreditCard,
  FileText,
  Flag,
  Gift,
  Globe,
  Handshake,
  House,
  ImagePlus,
  Landmark,
  Layers,
  Link,
  List,
  ListChecks,
  Menu,
  Monitor,
  Moon,
  OctagonAlert,
  Paperclip,
  Pencil,
  PiggyBank,
  Plus,
  QrCode,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Scale,
  Search,
  Send,
  Settings,
  SlidersHorizontal,
  Smartphone,
  Sun,
  Tag,
  Trash2,
  TriangleAlert,
  Upload,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * The single place icons are chosen. Features reference `iconFor('debts')`
 * (or import a named icon) so swapping the icon set later is one file.
 */
export const icons = {
  calendar: CalendarDays,
  subscriptions: Repeat,
  installments: Layers,
  checklist: ListChecks,
  debts: Scale,
  budgets: PiggyBank,
  tags: Tag,
  accounts: Briefcase,
  banks: Landmark,
  methods: Wallet,
  settings: Settings,
  overview: Menu,
  add: Plus,
  refresh: RefreshCw,
  transfer: ArrowLeftRight,
  card: CreditCard,
  cash: Banknote,
  transactions: ArrowLeftRight,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function iconFor(name: IconName): LucideIcon {
  return icons[name];
}

export type { LucideIcon };
export {
  ArrowLeftRight,
  Banknote,
  Bitcoin,
  Briefcase,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  Coins,
  CreditCard,
  FileText,
  Flag,
  Gift,
  Globe,
  Handshake,
  House,
  ImagePlus,
  Landmark,
  Layers,
  Link,
  List,
  ListChecks,
  Menu,
  Monitor,
  Moon,
  OctagonAlert,
  Paperclip,
  Pencil,
  PiggyBank,
  Plus,
  QrCode,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Scale,
  Search,
  Send,
  Settings,
  SlidersHorizontal,
  Smartphone,
  Sun,
  Tag,
  Trash2,
  TriangleAlert,
  Upload,
  Users,
  Wallet,
  X,
};
